### ISSUE TITLE
请教一下name，和reward_id是怎么对应起来的

### ISSUE THREAD

**Issue by Etuloser** [biuuu/gbf-card-rate#1]
能通过掉率公示拿到当前卡池所有物品 name 和 drop_rate
请问对应的 reward_id 是怎么获取的？

**Comment by biuuu** [comment]
这个是游戏里返回的数据自带的，你关闭了issue是已经知道了吗

**Comment by Etuloser** [comment]
> 这个是游戏里返回的数据自带的，你关闭了issue是已经知道了吗

是的，我仔细看了下源码了解了，丢人了，感谢回复！
